### ISSUE TITLE
Can we add the ability to mock websocket messages?

### ISSUE THREAD

**Issue by btvanhooser** [microsoft/playwright-sharp#1450] opened 2021-05-27 22:03 UTC
We have the ability to sniff websockets and use events on messages bi directionally, which is great, but can we also modify those messages? Either change them if they are fired, or send them directly to the websocket? It seems like following the "Route.ContinueAsync" flow works well, but it'd be even better if we can create a request since we already have the "WebSocket" class within the event handler.

**Comment by yury-s** [comment] 2021-05-27 23:11
Closing as duplicate of https://github.com/microsoft/playwright/issues/4488, please :+1:  for that issue if you'd like it to be implemented.

**Closed by yury-s** 2021-05-27 23:11 UTC
